### PR TITLE
Sprites

### PR DESCRIPTION
**Pull request by pconesa**
users:
  - New Icons.
  - Icons based on sprites, easier to resize or customized
  - New variable: SCIPION_SPRITES_FILE to point to a custom sprite. It should be compatible with sprites.png at pyworkflow/resources.
  - Scipion GUI log moved to the log tabs and removed from menu
  - New variable: SCIPION_SHOW_TEXT_IN_TOOLBAR, set it to anything to show the text of the icons below developers:
  - ProjectConfig class removed
  - New methods in path: hasChangedSince and isFileFinished
  - New method in utils: strToDuration (useful to translate "1h 35m" to seconds). For duration parameters.
  - New class Variable to be tested in Config class. A step towards a Config editing GUI.
  - SCIPION_DEBUG_SQLITE rescued to activate SQL clauses in debug.

### CODE REVIEW

**Review by JorMaister — CHANGES_REQUESTED** [review]
The icons look quite good! But, at least in my case, the protocol list panel on the left shows now the Beta labels very big. Am I missing something?

image

**Comment by pconesa** [comment]
@plosana will work on the other icons still to change. Once ready this can be merge. I change it to draft for now

**Comment by azazellochg** [comment]
Since you are working on this, could we please change the order of buttons? It takes me 5 seconds to find the stop protocol or browse button. The most used buttons should go first.

**Comment by pconesa** [comment]
That is not a common practice… most software group icons by “similar functionality”, may be the problema is tha icons are not enough? You alway have the resourc of learning the shortcuts!! 😉 We are far from customizing the order… not sure if we Will do it, but thanks, I’ll make a note….. what others (Reading this) think about this?.   De: Grigory SharovEnviado: miércoles, 10 de enero de 2024 13:09Para: scipion-em/scipion-pyworkflowCC: Pablo Conesa; AuthorAsunto: Re: [scipion-em/scipion-pyworkflow] Sprites (PR #490) Since you are working on this, could we please change the order of buttons? It takes me 5 seconds to find the stop protocol or browse button. The most used buttons should go first.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by plosana** [comment]
Hi everyone! I agree with Grigory that I find more intuitive a different order for the icons. I did a bit of a study grouping the icons by the functionality that they had and came up with this:
image

To me, a more intuitive order would be the one I propose below, but any ideas are welcome :) 
image

**Comment by delarosatrevin** [comment]
Patricia,

You are using nicer icons in your proposal screenshot, so biasing us toward
it. ;)

In any grouping, I suggest briefly asking some users and hiding some icons
for actions that are not used that frequently. (in my opinion, for example:
labels, workflow selected, etc)

Best,
Jose Miguel

**Comment by azazellochg** [comment]
@plosana that looks beautiful! Labels are definitely helpful, otherwise I often have to hover over every button to find the meaning 😁

**Comment by pconesa** [comment]
There is a variable to Show or not the labels. Do we want it active by default?

**Comment by azazellochg** [comment]
Yes please 🥺

**Comment by plosana** [comment]
Yes!! I believe it would be very very helpful

**Comment by JorMaister** [comment]
After the last changes, it looks nice! I've checked all the windows with icons and they all behave well in terms of appearance. My only question is regarding the "Browse" window, if the last two options of the toolbar ("Recent" and "Protocol folder") not have an associated icon, or it is not being displayed properly.

image

**Comment by JorMaister** [comment]
On the other hand, I had some execution problems when using this branch. Here's an example:

00001:   Traceback (most recent call last):
00002:     File "/home/jjimenez/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 203, in run
00003:       self._run()
00004:     File "/home/jjimenez/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 254, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/home/jjimenez/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 250, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/home/jjimenez/scipion3/scipion-em-emantomo/emantomo/protocols/protocol_template_matching.py", line 136, in prepareEmanPrj
00009:       self.convertOrLink(inTomoName, tomo.getTsId(), TOMOGRAMS_DIR, sRate)
00010:     File "/home/jjimenez/scipion3/scipion-em-emantomo/emantomo/protocols/protocol_base.py", line 208, in convertOrLink
00011:       self.convertBetweenHdfAndMrc(abspath(inFile), outFile, extraArgs=f'--apix {sRate:.3f}')
00012:     File "/home/jjimenez/scipion3/scipion-em-emantomo/emantomo/protocols/protocol_base.py", line 212, in convertBetweenHdfAndMrc
00013:       program = Plugin.getProgram("e2proc3d.py")
00014:     File "/home/jjimenez/scipion3/scipion-em-eman2/eman2/__init__.py", line 114, in getProgram
00015:       return f"{cls.getActivationCmd()} && {cmd} {program} "
00016:     File "/home/jjimenez/scipion3/scipion-em-eman2/eman2/__init__.py", line 108, in getActivationCmd
00017:       cls.getEmanEnvActivation())
00018:     File "/home/jjimenez/scipion3/scipion-em-eman2/eman2/__init__.py", line 100, in getEmanEnvActivation
00019:       scipionHome = Config.SCIPION_HOME + os.path.sep
00020:   TypeError: unsupported operand type(s) for +: 'Variable' and 'str'
00021:   Protocol failed: unsupported operand type(s) for +: 'Variable' and 'str'

**Comment by pconesa** [comment]
Thanks JOrge, I think we need to overload more methods of the Variable class. I'll fix it

**Comment by pconesa** [comment]
Those "actions" never had an icon.

**Comment by JorMaister** [comment]
Haha, my bad! Sorry

**Comment by JorMaister** [comment]
Solved! Thanks

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
