### PR TITLE
- SCIPION_USE_QUEUE: New variable, if defined (almost any value), new…

### PR DESCRIPTION
**Pull request by pconesa**
… protocols will be sent to queue by default.

### CODE REVIEW

**Review by JorMaister — APPROVED** [review]

**Comment by azazellochg** [comment]
@pconesa this is not working properly for me. Now every new protocol form I create has "Use queue = Yes" selected. I do not have this new var defined anywhere

**Comment by pconesa** [comment]
Thank and apologies... I'll have a look tomorrow.

**Comment by azazellochg** [comment]
No problem, just FYI :)

**Comment by pconesa** [comment]
Can you double check you do not have the variable?

It works fine here. 

I'll change it anyway cause if you have False  (String) in the config (as a consequence of "scipion3 config" it behaves as True

**Pull request merged**
