### PR TITLE
Add on location

### PR DESCRIPTION
**Pull request by pconesa**
- Add protocol is an icon.
  - Right clik on canvas offers to add a protocol on the clicked location.
  - Scipion log is a project.log (only for project events)

### CODE REVIEW

**Comment by azazellochg** [comment]
I was thinking, do we actually need the "protocol list" command? With hundreds of plugins I thought it's kind of pointless.

**Review by fonsecareyna82 — APPROVED** [review]

**Comment by pconesa** [comment]
I think it is useful when a user has a plugin issue. In this case.... it is for an attempt to feed an AI engine with a "readable text about protocols" to be trained and hopefully have a AI available for the users to ask anything and get a nice response and accurate (not reached so far)

**Comment by azazellochg** [comment]
Hm, I would argue that "scipion inspect plugin" is more useful. But okay, we can keep it for now :)

**Comment by azazellochg** [comment]
Can this new option be removed when right-clicking on a protocol box (not in empty space)?

**Pull request merged**
