### PR TITLE
Fixes when MANDATORY is in the host.conf and MPI/cores are above MAND…

### PR DESCRIPTION
**Pull request by pconesa**
…ATORY.

This should fix what @delarosatrevin reported today in slack. 

Prevoius code wasn't distinguishing between:

1.- useQueue = True and Queueparams populated
2.- useQueue = False (therefore else was never happening)

I do not have a queue engine locally to test this.

### CODE REVIEW

**Comment by pconesa** [comment]
But I think changes does not require it, all happens before submitting to the queue.

**Review by delarosatrevin — COMMENTED** [review]
Hi @pconesa , now it is working as expected. The Mandatory condition is taken into account and useQueue properly evaluated. 

One last comment that I would suggest. Queue parameters are important and sometimes changes from one job to another even if it is a copy. So, I will suggest, that despite some parameters are set for the queue, the Queue dialog should be open at least once before the protocol is executed. Not always as before, since now the user can edit the parameters, but at least one after the protocol form is opened.

**Comment by pconesa** [comment]
Thanks @delarosatrevin for reviewing it. 

I understand your suggestion. Te only way I see to implement that is to persist a flag!! I see it weird and probably the first time we need to do this. 

The way I see it is: 

1.- declare a Boolean "queueShown" (Scipion one) to persist the status (default = False)
2.- When copying it, reset it to false and when exporting it too (or importing it)
3.- Check this boolean at schedule/execute?

**Comment by delarosatrevin** [comment]
I was thinking of a simpler solution, not involving persistence at all.

1) every time the user opens a protocol form (either opening an existing one or copying a job) queueShown=False
2) If user edit queue params, queueShown=True
3) At "Execute", if queueShow == False, then open  the queue dialog

I guess in a scripting schenario, non-GUI,  scenario this does not make any sense.

**Comment by pconesa** [comment]
So, if the user saves and closes scipion (weird but possible), he might be asked again since there is no persistence. I'm ok with this though,

**Comment by delarosatrevin** [comment]
Yes, I think it is safer...queue jobs tend to be long, so it is better to "remind" users to set the queue parameters.

**Comment by pconesa** [comment]
@delarosatrevin , I believe I've addressed your suggestion.

**Comment by pconesa** [comment]
Now, I'm thinking maybe you wanted the boolean in the Form better?

**Comment by delarosatrevin** [comment]
> Now, I'm thinking maybe you wanted the boolean in the Form better?

No I don't want that. I think it is great as it is now.

**Comment by delarosatrevin** [comment]
Thanks a lot, @pconesa for addressing my latest comments. I'm happy to merge this PR and get it into a new release as soon as possible.

**Comment by pconesa** [comment]
I can't merge this unless someones approves it.

**Review by delarosatrevin — APPROVED** [review]
Done!

**Pull request merged**
