### PR TITLE
Review of protocol time (CPU time and Wall time)

### LINKED ISSUE #127: wrong time for the protocol run
To reproduce:
1. Run a protocol with several steps
2. Stop/abort/fail at a certain step
3. Continue protocol 

When I hover the mouse over finished protocol box the Time is shown only for the last steps that were run after 3. It should be a sum of all steps

### PR DESCRIPTION
**Pull request by pconesa**
Steps window:
 - Show status.
 - Reset status, useful in some cases when a step finishes and you want to run it again (createOutputStep outputting nothing after many hours of run)

Protocol:
 _setStatusStep --> renamed to a more generic _updateSteps, receiving a lambda (callback to do the update)
 cpuTime (NEW) Integer: incremented on every finished step.
 _finalizeStep --> To finish a step anytime is "closed" (finished, aborted, failed)
 setRunning (overwritten to keep initTime when RESUMING and therefore have a "better" Wall time.
viewprotocols.py: Tooltip showing CPU time and Wall time

Closes #127

### CODE REVIEW

**Comment by azazellochg** [comment]
Thank @pconesa , unfortunately protocol.py is too complex for me. Could you explain the difference bwt wall vs cpu time?

**Comment by pconesa** [comment]
No worries.

Wall time is the difference between initTime and end time. This is what we were showing before as Time. The only thing I've changed here is that init time is kept in any resume run mode:

eg:
Protocol starts at 00:00
It fails at 00:10 --> wall time is 10 minutes
You resume it immediately, and fails after 10 more minutes -> wall time is 20 minutes

Now , this value tries to answer ¿How much time elapsed? 

If after failing for the second time you leave it there, until 10:20. And then resume it again, and finishes after 40 minutes, wall time will be 11 hours!. So stall time is counted (10 hours). 

Now, CPU time is the sum of the duration of all the steps. In a serial step run, should be similar, in a parallel run CPU time should be higher. This was what initially we called B on the issue, wall time is A.

**Comment by azazellochg** [comment]
Brilliant, thank you!

**Comment by azazellochg** [comment]
I'll leave it to Yunior to review

**Comment by pconesa** [comment]
yes, thank you. @fonsecareyna82 ?

**Comment by fonsecareyna82** [comment]
I take care of it

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
