### PR TITLE
Jj fix issues

### PR DESCRIPTION
**Pull request by JorMaister**
Masks are now in red by default to provide a better experience (the blue ones were difficult to be distinguished from the gray scale background image). Other fixes.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
I think that blue is as visible as red one here...and red is usually associated with errors in GUI.

**Comment by pconesa** [comment]
We've also discussed to have a ring instead. What about that?

**Comment by azazellochg** [comment]
Maybe a blue mask with a thick opaque ring is better? This way when you have a wizard for two masks simultaneously (e.g. inner and outer radius masks) it would be more visible.

**Comment by JorMaister** [comment]
Maybe the best option is to leave it as it was before until we reach a consensus about the appearance of the mask in case it's considered to be necessary. I can close this PR if you all agree.

**Comment by delarosatrevin** [comment]
@JorMaister I agree that this may not be the more important thing and it might take some time to reach a consensus and implement changes that make everyone happy ;)
I'm fine if this PR is closed.

**Comment by pconesa** [comment]
I'm closing this, I liked red, but there is no point to continue discussing about the color. Thank you all!

**Pull request closed without merging**
