### PR TITLE
Fix continue for protocol Steps

### PR DESCRIPTION
**Pull request by delarosatrevin**
There is a bug that is causing that protocols "continue" mode does not work.
It is caused because picking dumps/loads bytes instead of str. So, there were two issues:
* Step arguments always evaluated different and continue did not found the proper step where to start
* In case that steps stores some "resultFiles" it was raising an error due to the encode('utf-8') call

Solution:
* Using json instead of pickle to store/retrieve with String

### CODE REVIEW

**Comment by pconesa** [comment]
Good catch!! I'll find time to test it although seems very straight forward.

**Comment by delarosatrevin** [comment]
@pconesa Please do not merge this PR yet. There is something with the order of the parameters that I'm investigating. So, the continue is not working yet.

**Comment by delarosatrevin** [comment]
False alarm, these changes are working. The problem was in the way we were constructing the command line for some Relion protocols, using a dict and later creating an string. If it is not an OrderedDict, then there is no order guarantee and it was a different string every time, despite being the same parameters.

**Comment by pconesa** [comment]
ready to review/merge then?

**Pull request merged**
