### PR TITLE
Update wizard mask color to improve the contrast and the consequently…

### PR DESCRIPTION
**Pull request by JorMaister**
… visualization.
Add config variable to make it customizable by the user.

Default color:
image
Custom color example 1:
image
Custom color example 2:
image

### CODE REVIEW

**Comment by azazellochg** [comment]
I think any color could work, so we dont argue about the color. What I think is that you need to highlight disc edge (make it a ring) so that both edges are visible more clearly.

**Comment by JorMaister** [comment]
I think it's a good idea to highlight the edge/s of the mask. I can adapt it to any suggestion, because I'm not an user, so I would be pleased if I receive any recommendation, in order to offer the best experience for the user. I think these kind of small details are important. About the edge, should it show some thickness? Which color? Because I was thinking in black, but may be difficult to distinguish in case the background image is dark gray.
On the other hand, I think that color customization is the best option to make this feature more user-friendly, as long as different people can perceive the contrast better under different conditions. But, I've kept the blue as default, chosing a lighter blue to enhance contrast. Anycase, I can remove the customization feature if you think it should be.
Thanks in advance.

**Comment by azazellochg** [comment]
Thanks Jorge, yes I think the edge should have 2-3px thickness and it
should be solid color

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by JorMaister** [comment]
@azazellochg,
This is the new result. Please, let me know your thoughts about it.
image

**Pull request merged**
