### PR TITLE
Avoid  locks

### PR DESCRIPTION
**Pull request by pconesa**
I'd like to propose these changes to be sent to devel.

it has this mapper.close, that will degrade performance when using myset[id].

This is rarely used, mainly in GUI stuff. I don't see any protocol step getting items this way. So very unlikely we are iterating a set using the __item__ method.

It also has some performance tweaks to avoid the get(id).
And removes the locks reported by @azazellochg in #116 

If we see, closing the mapper is bad, we can always commend that back quicliy and speed it up, but getting the lock again:
https://github.com/scipion-em/scipion-pyworkflow/compare/avoid-some-locks?expand=1#diff-2832a69507ad8860cc7c522f6cc4bd92fd2df723268184e6b65a8eafdb47b262R1098

### CODE REVIEW

**Comment by azazellochg** [comment]
Hi @pconesa , is set[id] used in the following examples?
image

**Comment by pconesa** [comment]
Thanks @azazelloatchg , I'd say yes, Ill review all that code, specially code in iteration lines.
Viewers should be fine, tests too. My concern is about protocol step. I'll review all.

**Comment by pconesa** [comment]
I've looked at the code in the screenshot. In summary code inside viewers (gctf, eman, cistem) is fine...actually, I think is never used since is a "Link" from showJ to offer "actions".  

Test are fine too and my only concern is about:

sphire convert and export ctf: in both the case is similar, iterating though ctfs and getting the mic with micid (taken from the ctf).

I'm going to measure the impact and come back. We might be able to replace it with iterItems (id=micId) or have a explicit method to get a single item by id with a flag to close or not the connection.

**Comment by pconesa** [comment]
One more thing, I'm not able to locate protocol_import.py code. Which plugin/branch isis from?

**Comment by pconesa** [comment]
Found a good balance. Turns out that Set.getFirstItem() is used in a similar scenario and is closing the mapper only if it was created ad-hoc inside. Same here. 

I've benchmark this and behaves similar to production when used in a loop (so mapper is not closed/opened each iteration.

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
